# Generated by Django 5.0.4 on 2024-05-13 17:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="basemodel_ptr",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="basemodel_ptr",
        ),
        migrations.RemoveField(
            model_name="order",
            name="basemodel_ptr",
        ),
        migrations.RemoveField(
            model_name="return",
            name="basemodel_ptr",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_id",
        ),
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=django.utils.timezone.now,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dispute",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="return",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="return",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="dispute_reason",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status_tracking",
            field=models.IntegerField(
                choices=[
                    (1, "RAISED"),
                    (2, "ACTIVE"),
                    (3, "INACTIVE"),
                    (4, "CLOSED"),
                    (5, "DUPLICATE"),
                ],
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="return_reason",
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name="BaseModel",
        ),
    ]
