# Generated by Django 5.0.4 on 2024-05-13 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0002_remove_customer_basemodel_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="return",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="return",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="customer",
            name="basemodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="amazon.basemodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dispute",
            name="basemodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="amazon.basemodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="basemodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="amazon.basemodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="return",
            name="basemodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="amazon.basemodel",
            ),
            preserve_default=False,
        ),
    ]
